"""End-to-end tool tests. Heavy deps (LayerD/PaddleOCR/Qwen) are optional —
the LayerD CV fallback is exercised here."""

from __future__ import annotations

from pathlib import Path

from imglayers_mcp.config import Config
from imglayers_mcp.core.orchestrator import Orchestrator
from imglayers_mcp.storage.projects import ProjectStore
from imglayers_mcp.tools import (
    decompose_image,
    derive_codegen_plan,
    export_project,
    get_layer,
    get_manifest,
    list_layers,
    render_annotated_preview_tool,
    render_preview,
)


def _make_runtime(tmp_path: Path) -> tuple[Orchestrator, ProjectStore]:
    config = Config(
        project_root=tmp_path / "projects",
        qwen_enabled=False,
        force_cpu=True,
        default_max_side=2048,
        default_detail="balanced",
        default_engine="auto",
    )
    store = ProjectStore(config.project_root)
    return Orchestrator(config, store), store


def test_decompose_image_end_to_end(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    res = decompose_image(
        orch,
        {
            "input_uri": str(synth_banner),
            "engine": "auto",
            "enable_ocr": True,
            "detail_level": "balanced",
            "export_formats": ["manifest", "svg", "codegen-plan"],
        },
    )
    assert res["project_id"].startswith("proj_")
    assert res["engine_selected"] in ("layerd", "qwen-layered")
    assert res["stats"]["total_layers"] >= 2  # background + at least one foreground

    pid = res["project_id"]
    paths = store.get(pid)
    assert paths.manifest_path.exists()
    assert paths.preview_path.exists()
    assert (paths.exports_dir / "export.svg").exists()
    assert (paths.exports_dir / "codegen-plan.json").exists()
    # At least one layer asset was written.
    assert any(paths.layers_dir.glob("*.png"))


def test_get_manifest_list_and_get_layer(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    out = decompose_image(orch, {"input_uri": str(synth_banner), "engine": "auto", "enable_ocr": True})
    pid = out["project_id"]

    gm = get_manifest(store, {"project_id": pid})
    assert gm["manifest"]["projectId"] == pid

    layers = list_layers(store, {"project_id": pid})["layers"]
    assert layers, "expected at least one layer"
    first = layers[0]
    detail = get_layer(store, {"project_id": pid, "layer_id": first["id"]})["layer"]
    assert detail["id"] == first["id"]


def test_render_preview_regenerates(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    out = decompose_image(orch, {"input_uri": str(synth_banner)})
    pid = out["project_id"]
    r = render_preview(store, {"project_id": pid, "output_name": "preview_v2.png"})
    assert r["preview_uri"].endswith("preview_v2.png")
    paths = store.get(pid)
    assert (paths.preview_dir / "preview_v2.png").exists()


def test_export_project_formats(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    out = decompose_image(orch, {"input_uri": str(synth_banner)})
    pid = out["project_id"]
    res = export_project(store, {"project_id": pid, "formats": ["svg", "codegen-plan", "preview", "manifest"]})
    assert "svg" in res["exports"]
    assert "codegen_plan" in res["exports"]
    assert res["exports"]["manifest"].endswith("/manifest")


def test_derive_codegen_plan(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    out = decompose_image(orch, {"input_uri": str(synth_banner)})
    pid = out["project_id"]
    plan = derive_codegen_plan(store, {"project_id": pid, "target": "react"})["plan"]
    assert plan["target"] == "react"
    assert "nodes" in plan
    assert "components" in plan


def test_annotated_preview_auto_generated(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    res = decompose_image(orch, {"input_uri": str(synth_banner)})
    # Auto-generated by decompose_image.
    assert res["annotated_preview_uri"].endswith("preview_annotated.png")
    assert res["grid_preview_uri"].endswith("preview_grid.png")
    paths = store.get(res["project_id"])
    assert (paths.preview_dir / "preview_annotated.png").exists()
    assert (paths.preview_dir / "preview_grid.png").exists()


def test_render_annotated_preview_tool_styles(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    res = decompose_image(orch, {"input_uri": str(synth_banner)})
    pid = res["project_id"]

    overlay = render_annotated_preview_tool(
        store,
        {"project_id": pid, "style": "overlay", "output_name": "annot_v2.png"},
    )
    assert overlay["preview_uri"].endswith("annot_v2.png")
    assert overlay["style"] == "overlay"

    grid = render_annotated_preview_tool(
        store,
        {"project_id": pid, "style": "grid", "output_name": "grid_v2.png", "columns": 2},
    )
    assert grid["preview_uri"].endswith("grid_v2.png")
    paths = store.get(pid)
    assert (paths.preview_dir / "annot_v2.png").exists()
    assert (paths.preview_dir / "grid_v2.png").exists()


def test_list_layers_filter(synth_banner: Path, tmp_path: Path) -> None:
    orch, store = _make_runtime(tmp_path)
    out = decompose_image(orch, {"input_uri": str(synth_banner)})
    pid = out["project_id"]
    filtered = list_layers(
        store,
        {"project_id": pid, "filter": {"type": "image", "editable_only": True}},
    )["layers"]
    assert all(l["type"] == "image" for l in filtered)
